name: CI Python Secure Build

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check dependencies for vulnerabilities
        run: |
          pip install safety
          safety check -r requirements.txt

      - name: Run security scan with Bandit
        run: |
          pip install bandit
          bandit -r .

      - name: Run tests
        run: |
          pip install pytest
          pytest

      - name: Display PR title
        run: echo "Titre PR : Create vuln.py"

      - name: Run application
        run: python code_vuln.py
